# Generated by Django 4.0.3 on 2023-12-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hats_rest', '0004_alter_hat_location_alter_locationvo_import_href'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationvo',
            name='shelf_number',
            field=models.PositiveSmallIntegerField(max_length=100, null=True),
        ),
    ]
