# Generated by Django 4.0.3 on 2023-12-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hats_rest', '0007_rename_hat_url_hat_hat_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationvo',
            name='import_href',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
    ]
