# Generated by Django 4.0.3 on 2023-12-13 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='binvo',
            old_name='closet_name',
            new_name='name',
        ),
    ]
