# Generated by Django 4.0.3 on 2023-12-13 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0002_rename_closet_name_binvo_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='binvo',
            old_name='name',
            new_name='closet_name',
        ),
    ]
