# Generated by Django 4.0.3 on 2023-12-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0003_rename_name_binvo_closet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='picture_url',
            field=models.URLField(null=True),
        ),
    ]
