# Generated by Django 4.0.3 on 2023-12-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0004_shoes_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='picture_url',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
